// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code_error.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Int code error description.
type IntCodeError struct {
	// Error level.
	Level Level `protobuf:"varint,1,opt,name=level,proto3,enum=errors.Level" json:"level,omitempty"`
	// Error code.
	Code int64 `protobuf:"zigzag64,2,opt,name=code,proto3" json:"code,omitempty"`
	// Message is explain the error code.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Detail of the error.
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// Error caller.
	Caller               *Caller  `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntCodeError) Reset()         { *m = IntCodeError{} }
func (m *IntCodeError) String() string { return proto.CompactTextString(m) }
func (*IntCodeError) ProtoMessage()    {}
func (*IntCodeError) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ca2332ac24edea, []int{0}
}

func (m *IntCodeError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntCodeError.Unmarshal(m, b)
}
func (m *IntCodeError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntCodeError.Marshal(b, m, deterministic)
}
func (m *IntCodeError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntCodeError.Merge(m, src)
}
func (m *IntCodeError) XXX_Size() int {
	return xxx_messageInfo_IntCodeError.Size(m)
}
func (m *IntCodeError) XXX_DiscardUnknown() {
	xxx_messageInfo_IntCodeError.DiscardUnknown(m)
}

var xxx_messageInfo_IntCodeError proto.InternalMessageInfo

func (m *IntCodeError) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_Normal
}

func (m *IntCodeError) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *IntCodeError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *IntCodeError) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *IntCodeError) GetCaller() *Caller {
	if m != nil {
		return m.Caller
	}
	return nil
}

// Uint code error description.
type UintCodeError struct {
	// Error level.
	Level Level `protobuf:"varint,1,opt,name=level,proto3,enum=errors.Level" json:"level,omitempty"`
	// Error code.
	Code uint64 `protobuf:"fixed64,2,opt,name=code,proto3" json:"code,omitempty"`
	// Message is explain the error code.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Detail of the error.
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// Error caller.
	Caller               *Caller  `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UintCodeError) Reset()         { *m = UintCodeError{} }
func (m *UintCodeError) String() string { return proto.CompactTextString(m) }
func (*UintCodeError) ProtoMessage()    {}
func (*UintCodeError) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ca2332ac24edea, []int{1}
}

func (m *UintCodeError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UintCodeError.Unmarshal(m, b)
}
func (m *UintCodeError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UintCodeError.Marshal(b, m, deterministic)
}
func (m *UintCodeError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UintCodeError.Merge(m, src)
}
func (m *UintCodeError) XXX_Size() int {
	return xxx_messageInfo_UintCodeError.Size(m)
}
func (m *UintCodeError) XXX_DiscardUnknown() {
	xxx_messageInfo_UintCodeError.DiscardUnknown(m)
}

var xxx_messageInfo_UintCodeError proto.InternalMessageInfo

func (m *UintCodeError) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_Normal
}

func (m *UintCodeError) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UintCodeError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UintCodeError) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *UintCodeError) GetCaller() *Caller {
	if m != nil {
		return m.Caller
	}
	return nil
}

// String code error description.
type StringCodeError struct {
	// Error level.
	Level Level `protobuf:"varint,1,opt,name=level,proto3,enum=errors.Level" json:"level,omitempty"`
	// Error code.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Message is explain the error code.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Detail of the error.
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// Error caller.
	Caller               *Caller  `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringCodeError) Reset()         { *m = StringCodeError{} }
func (m *StringCodeError) String() string { return proto.CompactTextString(m) }
func (*StringCodeError) ProtoMessage()    {}
func (*StringCodeError) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ca2332ac24edea, []int{2}
}

func (m *StringCodeError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringCodeError.Unmarshal(m, b)
}
func (m *StringCodeError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringCodeError.Marshal(b, m, deterministic)
}
func (m *StringCodeError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringCodeError.Merge(m, src)
}
func (m *StringCodeError) XXX_Size() int {
	return xxx_messageInfo_StringCodeError.Size(m)
}
func (m *StringCodeError) XXX_DiscardUnknown() {
	xxx_messageInfo_StringCodeError.DiscardUnknown(m)
}

var xxx_messageInfo_StringCodeError proto.InternalMessageInfo

func (m *StringCodeError) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_Normal
}

func (m *StringCodeError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *StringCodeError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StringCodeError) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *StringCodeError) GetCaller() *Caller {
	if m != nil {
		return m.Caller
	}
	return nil
}

func init() {
	proto.RegisterType((*IntCodeError)(nil), "errors.IntCodeError")
	proto.RegisterType((*UintCodeError)(nil), "errors.UintCodeError")
	proto.RegisterType((*StringCodeError)(nil), "errors.StringCodeError")
}

func init() { proto.RegisterFile("code_error.proto", fileDescriptor_50ca2332ac24edea) }

var fileDescriptor_50ca2332ac24edea = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0x4f, 0x49,
	0x8d, 0x4f, 0x2d, 0x2a, 0xca, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x73,
	0x8a, 0xa5, 0xb8, 0x73, 0x52, 0xcb, 0x52, 0x73, 0x20, 0x82, 0x52, 0x3c, 0xc9, 0x89, 0x39, 0x39,
	0xa9, 0x50, 0x25, 0x4a, 0x0b, 0x19, 0xb9, 0x78, 0x3c, 0xf3, 0x4a, 0x9c, 0xf3, 0x53, 0x52, 0x5d,
	0x41, 0x8a, 0x85, 0x94, 0xb9, 0x58, 0xc1, 0xaa, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x78,
	0xf5, 0x20, 0x66, 0xe8, 0xf9, 0x80, 0x04, 0x83, 0x20, 0x72, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0xcb,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x84, 0x82, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2,
	0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8c, 0x8b,
	0x2d, 0x25, 0xb5, 0x24, 0x31, 0x33, 0x47, 0x82, 0x05, 0x2c, 0x01, 0xe5, 0x09, 0xa9, 0x71, 0xb1,
	0x41, 0xdc, 0x22, 0xc1, 0xa6, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0x07, 0xb3, 0xcb, 0x19, 0x2c, 0x1a,
	0x04, 0x95, 0x55, 0x5a, 0xc4, 0xc8, 0xc5, 0x1b, 0x9a, 0x49, 0x91, 0x23, 0xd9, 0x68, 0xee, 0xc8,
	0x25, 0x8c, 0x5c, 0xfc, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x14, 0x38, 0x93, 0x93, 0xd6, 0xce,
	0x4c, 0x62, 0x03, 0x47, 0xbb, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x44, 0x87, 0x88, 0x58, 0x2d,
	0x02, 0x00, 0x00,
}
