// Code generated by protoc-gen-go. DO NOT EDIT.
// source: level.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Level.
type Level int32

const (
	// Debug level have error caller and print stack trace.
	Level_Debug Level = 0
	// Normal level have no error caller and stack trace.
	Level_Normal Level = 1
	// Error level have error caller and stack trace.
	Level_Error Level = 2
	// Panic level have error caller and print stack trace, then panic error.
	Level_Panic Level = 3
)

var Level_name = map[int32]string{
	0: "Debug",
	1: "Normal",
	2: "Error",
	3: "Panic",
}

var Level_value = map[string]int32{
	"Debug":  0,
	"Normal": 1,
	"Error":  2,
	"Panic":  3,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8d18daab47a3117, []int{0}
}

func init() {
	proto.RegisterEnum("errors.Level", Level_name, Level_value)
}

func init() { proto.RegisterFile("level.proto", fileDescriptor_c8d18daab47a3117) }

var fileDescriptor_c8d18daab47a3117 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x49, 0x2d, 0x4b,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2d, 0x2a, 0xca, 0x2f, 0x2a, 0xd6,
	0x32, 0xe1, 0x62, 0xf5, 0x01, 0x09, 0x0b, 0x71, 0x72, 0xb1, 0xba, 0xa4, 0x26, 0x95, 0xa6, 0x0b,
	0x30, 0x08, 0x71, 0x71, 0xb1, 0xf9, 0xe5, 0x17, 0xe5, 0x26, 0xe6, 0x08, 0x30, 0x82, 0x84, 0x5d,
	0x41, 0x2a, 0x05, 0x98, 0x40, 0xcc, 0x80, 0xc4, 0xbc, 0xcc, 0x64, 0x01, 0xe6, 0x24, 0x36, 0xb0,
	0x21, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0xff, 0xbf, 0xf6, 0x53, 0x00, 0x00, 0x00,
}
